### ISSUE TITLE
Exe source code please and md5?

### ISSUE THREAD

**Issue by pryorda** [SecureThisShit/WinPwn#1]

**Comment by SecureThisShit** [comment]
Its PSAttack "https://github.com/jaredhaight/PSAttack" build with "https://github.com/jaredhaight/PSAttackBuildTool". 
If you dont trust me just delete the executable and build it yourself from the mentioned Repositories. An alternative would be https://github.com/Cn33liz/p0wnedShell, im planing to integrate WinPwn there in my forked version.

**Comment by pryorda** [comment]
👍
